const cfg=window.APP_CONFIG||{};const sb=window.supabase?.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);const $=id=>document.getElementById(id);let editing=null;let me=null;let mediaKind='image';let mediaItems=[];
function configured(){return sb&&!cfg.SUPABASE_URL.includes('TU-PROYECTO')&&!cfg.SUPABASE_PUBLISHABLE_KEY.includes('TU_PUBLISHABLE')}
async function init(){if(!configured()){$('loginMsg').textContent='Primero configura config.js con la URL y Publishable Key de Supabase.';return}const {data:{session}}=await sb.auth.getSession();if(session)await showDashboard()}
async function login(e){e.preventDefault();setMsg('loginMsg','Entrando…');const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)setMsg('loginMsg',error.message);else await showDashboard()}
async function showDashboard(){const {data:user}=await sb.auth.getUser();me=user?.user;if(!me){location.reload();return}const {data:p,error}=await sb.from('profiles').select('*').eq('id',me.id).single();if(error||!p){$('loginMsg').textContent='Tu usuario no tiene perfil. Ejecuta el SQL de v8.5 en Supabase.';return}if(p.role!=='admin'){location.href='../owner/';return}$('loginPanel').classList.add('hidden');$('dashboard').classList.remove('hidden');await loadList();await loadOwners()}
async function loadList(){const {data,error}=await sb.from('businesses').select('*').order('created_at',{ascending:false});if(error){$('list').innerHTML='<p>'+esc(error.message)+'</p>';return}$('list').innerHTML=(data||[]).map(b=>`<div class="business-row"><div><strong>${esc(b.name)}</strong><div class="small">${esc(b.category||'')} · <span class="badge ${b.active?'on':''}">${b.active?'Activo':'Inactivo'}</span></div></div><div><button class="secondary" onclick='editBusiness(${JSON.stringify(b).replace(/</g,"\\u003c")})'>Editar</button></div></div>`).join('')||'<p>No hay negocios todavía.</p>'}
async function loadOwners(){const {data:profiles,error}=await sb.from('profiles').select('*').order('email');if(error){$('ownersList').innerHTML='<p>'+esc(error.message)+'</p>';return}const {data:links}=await sb.from('business_users').select('business_id,user_id');const businesses=(await sb.from('businesses').select('id,name')).data||[];const map=new Map(businesses.map(b=>[b.id,b.name]));$('ownerSelect').innerHTML=(profiles||[]).filter(p=>p.role==='owner').map(p=>`<option value="${p.id}">${esc(p.email)}${p.full_name?' · '+esc(p.full_name):''}</option>`).join('')||'<option value="">No hay propietarios registrados</option>';$('ownerBusinessSelect').innerHTML=businesses.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('');$('ownersList').innerHTML=(profiles||[]).filter(p=>p.role==='owner').map(p=>{const mine=(links||[]).filter(x=>x.user_id===p.id).map(x=>map.get(x.business_id)).filter(Boolean);return `<div class="business-row"><div><strong>${esc(p.email)}</strong><div class="small">${mine.length?mine.map(esc).join(', '):'Sin negocios asignados'}</div></div></div>`}).join('')||'<p>No hay propietarios. Pídeles que se registren desde Acceso propietarios.</p>'}
function newBusiness(){editing=null;$('businessForm').reset();$('id').value='';$('editorTitle').textContent='Nuevo negocio';$('currentTarget').textContent='';$('formMsg').textContent='';$('editor').classList.remove('hidden');$('mediaPanel').classList.add('hidden')}
window.editBusiness=async b=>{editing=b;$('editorTitle').textContent='Editar negocio';for(const k of ['id','name','category','description','phone','whatsapp','website','instagram','address','offer','sponsor_name','sponsor_url'])if($(k))$(k).value=b[k]||'';$('active').value=String(!!b.active);$('target').value='';$('currentTarget').textContent=b.target_path?'Imagen actual: '+b.target_path:'Sin imagen';$('formMsg').textContent='';$('editor').classList.remove('hidden');$('mediaPanel').classList.remove('hidden');await loadMedia();window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
async function save(e){e.preventDefault();setMsg('formMsg','Guardando…');const id=$('id').value||crypto.randomUUID();let path=editing?.target_path||'';const file=$('target').files[0];if(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';path=`${id}.${ext}`;const {error:up}=await sb.storage.from('targets').upload(path,file,{upsert:true,contentType:file.type});if(up){setMsg('formMsg','Error al subir imagen: '+up.message);return}}const payload={id,name:$('name').value.trim(),category:$('category').value.trim(),description:$('description').value.trim(),phone:$('phone').value.trim(),whatsapp:$('whatsapp').value.trim(),website:$('website').value.trim(),instagram:$('instagram').value.trim(),address:$('address').value.trim(),offer:$('offer').value.trim(),sponsor_name:$('sponsor_name').value.trim(),sponsor_url:$('sponsor_url').value.trim(),target_path:path,active:$('active').value==='true',updated_at:new Date().toISOString()};const {error}=await sb.from('businesses').upsert(payload);if(error){setMsg('formMsg',error.message);return}editing={...(editing||{}),...payload};setMsg('formMsg','Guardado correctamente.');await loadList();setTimeout(()=>{$('editor').classList.add('hidden');$('mediaPanel').classList.add('hidden')},500)}
async function loadMedia(){if(!editing)return;const {data,error}=await sb.from('business_media').select('*').eq('business_id',editing.id).order('media_type').order('sort_order').order('created_at');if(error){$('mediaMsg').textContent='No se pudo cargar el contenido: '+error.message;return}mediaItems=data||[];renderMedia()}
function bucketFor(t){return t==='image'?'media-images':t==='audio'?'media-audio':'media-video'}
function publicMediaUrl(m){return sb.storage.from(bucketFor(m.media_type)).getPublicUrl(m.storage_path).data.publicUrl}
function previewHtml(m,url){if(m.media_type==='image')return `<img src="${escAttr(url)}" alt="">`;if(m.media_type==='video')return `<video src="${escAttr(url)}" controls preload="metadata"></video>`;return `<audio src="${escAttr(url)}" controls preload="metadata"></audio>`}
function renderMedia(){const items=mediaItems.filter(x=>x.media_type===mediaKind);if(!items.length){$('mediaList').innerHTML='<p class="small">Todavía no hay contenidos de este tipo.</p>';return}$('mediaList').innerHTML=items.map((m,i)=>{const url=publicMediaUrl(m);return `<div class="media-item"><div class="media-preview">${previewHtml(m,url)}</div><div class="media-meta"><strong>${esc(m.title||'Sin título')}</strong><p>${esc(m.description||'')}</p><span class="small">${m.active?'Publicado':'Oculto'} · ${esc(m.mime_type||'')}</span></div><div class="media-actions"><button type="button" class="secondary" onclick="moveMedia('${m.id}',-1)" ${i===0?'disabled':''}>↑</button><button type="button" class="secondary" onclick="moveMedia('${m.id}',1)" ${i===items.length-1?'disabled':''}>↓</button><button type="button" class="secondary" onclick="editMedia('${m.id}')">Editar</button><button type="button" class="secondary" onclick="toggleMedia('${m.id}')">${m.active?'Ocultar':'Publicar'}</button><button type="button" class="secondary" onclick="deleteMedia('${m.id}')">Eliminar</button></div></div>`}).join('')}
function allowed(type,file){return !!file&&((type==='image'&&file.type.startsWith('image/'))||(type==='audio'&&file.type.startsWith('audio/'))||(type==='video'&&file.type.startsWith('video/')))}
async function uploadMedia(){if(!editing)return;const file=$('mediaFile').files[0];if(!allowed(mediaKind,file)){setMsg('mediaMsg','Selecciona un archivo válido para la pestaña actual.');return}if(file.size>50*1024*1024){setMsg('mediaMsg','El archivo supera 50 MB.');return}setMsg('mediaMsg','Subiendo…');const bucket=bucketFor(mediaKind);const ext=(file.name.split('.').pop()||'bin').toLowerCase().replace(/[^a-z0-9]/g,'')||'bin';const path=`${editing.id}__${crypto.randomUUID()}.${ext}`;const {error:up}=await sb.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(up){setMsg('mediaMsg','Error al subir: '+up.message);return}const order=mediaItems.filter(x=>x.media_type===mediaKind).length;const {error:dbErr}=await sb.from('business_media').insert({business_id:editing.id,media_type:mediaKind,storage_path:path,mime_type:file.type,title:$('mediaTitle').value.trim(),description:$('mediaDescription').value.trim(),sort_order:order,active:true});if(dbErr){await sb.storage.from(bucket).remove([path]);setMsg('mediaMsg','No se pudo registrar: '+dbErr.message);return}$('mediaFile').value='';$('mediaTitle').value='';$('mediaDescription').value='';setMsg('mediaMsg','Contenido añadido correctamente.');await loadMedia()}
window.editMedia=async id=>{const m=mediaItems.find(x=>x.id===id);if(!m)return;const title=prompt('Título:',m.title||'');if(title===null)return;const description=prompt('Descripción:',m.description||'');if(description===null)return;const {error}=await sb.from('business_media').update({title,description,updated_at:new Date().toISOString()}).eq('id',id);setMsg('mediaMsg',error?'Error: '+error.message:'Contenido actualizado.');await loadMedia()}
window.toggleMedia=async id=>{const m=mediaItems.find(x=>x.id===id);if(!m)return;const {error}=await sb.from('business_media').update({active:!m.active,updated_at:new Date().toISOString()}).eq('id',id);setMsg('mediaMsg',error?'Error: '+error.message:(m.active?'Contenido ocultado.':'Contenido publicado.'));await loadMedia()}
window.moveMedia=async(id,delta)=>{const items=mediaItems.filter(x=>x.media_type===mediaKind);const idx=items.findIndex(x=>x.id===id);const ni=idx+delta;if(idx<0||ni<0||ni>=items.length)return;const a=items[idx],b=items[ni];const {error:e1}=await sb.from('business_media').update({sort_order:b.sort_order,updated_at:new Date().toISOString()}).eq('id',a.id);if(e1){setMsg('mediaMsg','Error al ordenar: '+e1.message);return}const {error:e2}=await sb.from('business_media').update({sort_order:a.sort_order,updated_at:new Date().toISOString()}).eq('id',b.id);if(e2){setMsg('mediaMsg','Error al ordenar: '+e2.message);return}await loadMedia()}
window.deleteMedia=async id=>{const m=mediaItems.find(x=>x.id===id);if(!m||!confirm('¿Eliminar este contenido?'))return;const {error:re}=await sb.storage.from(bucketFor(m.media_type)).remove([m.storage_path]);if(re){setMsg('mediaMsg','No se pudo eliminar el archivo: '+re.message);return}const {error}=await sb.from('business_media').delete().eq('id',id);setMsg('mediaMsg',error?error.message:'Contenido eliminado.');await loadMedia()}
async function assignOwner(){const uid=$('ownerSelect').value,bid=$('ownerBusinessSelect').value;if(!uid||!bid){setMsg('ownerMsg','Selecciona propietario y negocio.');return}const {error}=await sb.from('business_users').upsert({user_id:uid,business_id:bid});setMsg('ownerMsg',error?'Error: '+error.message:'Permiso concedido correctamente.');await loadOwners()}
async function logout(){await sb.auth.signOut();location.reload()}function setMsg(id,m){$(id).textContent=m}function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}function escAttr(s){return esc(s)}
$('loginForm').addEventListener('submit',login);$('businessForm').addEventListener('submit',save);$('newBtn').addEventListener('click',newBusiness);$('cancelBtn').addEventListener('click',()=>$('editor').classList.add('hidden'));$('logoutBtn').addEventListener('click',logout);$('assignBtn').addEventListener('click',assignOwner);$('uploadMediaBtn').addEventListener('click',uploadMedia);document.querySelectorAll('.media-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.media-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');mediaKind=btn.dataset.kind;$('mediaFile').accept=mediaKind==='image'?'image/*':mediaKind==='audio'?'audio/*':'video/*';renderMedia()}));init();
